#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication foamCleanCase
echo "Case cleaned."

touch foam.foam

cp system/blockMeshDict.orig system/blockMeshDict
runApplication blockMesh

#cp constant/dynamicMeshDict.orig constant/dynamicMeshDict

runApplication decomposePar
runParallel $(getApplication)
